import { Request, Response } from 'express';

export const handleIngest = async (req: Request, res: Response): Promise<void> => {
    try {
        const { inputType, content } = req.body;

        if (!content) {
            res.status(400).json({ status: "error", message: "Missing content payload" });
            return;
        }

        // TODO: Wire up OpenAI Vision API and Web Scraper later
        console.log(`[Ingest] Received ${inputType} data. Normalizing...`);

        // IMMEDIATELY RETURN MOCK DATA TO UNBLOCK FRONTEND
        res.status(200).json({
            status: "success",
            data: {
                verdict: "Unverified",
                trustScore: 40,
                claimSummary: "This is a mock claim summary generated by the ingest controller.",
                evidenceLinks: [],
                safetyFlags: [
                    {
                        type: "Mock Phishing Risk",
                        description: "The backend routing is successfully connected, but AI logic is pending."
                    }
                ],
                privacyRisk: {
                    score: "C",
                    trackersFound: 2
                }
            }
        });
    } catch (error) {
        console.error("[Ingest Error]:", error);
        res.status(500).json({ status: "error", message: "Internal Server Error" });
    }
};